### ISSUE TITLE
User Manager problem, users and groups are missing (eXist-db 3.1.1)

### ISSUE THREAD

**Issue by welblaud** [eXist-db/dashboard#55] opened 2017-04-05 13:57 UTC
In the version 3.1.1 the User Manager package does not work properly. If I check Remember Me checkbox during logging in, there are neither users nor groups listed. There is only “We are sorry, an error has happened”. It is interesting the sentence is in Czech, hence it could somehow be associated with browsers or Java plugin (tested in Firefox 52.0.2 and IE 11). As soon as I uncheck the box during logging in, User Manager works as expected.

**Comment by joewiz** [comment] 2017-04-05 15:02
Dupe of https://github.com/eXist-db/dashboard/issues/44?

**Comment by welblaud** [comment] 2017-04-05 15:11
Oh, it seems so! Adam asked me to raise the issue earlier today. Thanks!

**Comment by joewiz** [comment] 2017-04-05 21:25
Closed as a dupe of #44.

**Closed** 2017-04-05 21:25 UTC
